version: '3.8'

services:
  php:
    container_name: "${CONTAINER_NAME}-${PHP_VERSION}"
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./public:/var/www
      - ./docker/php/configs:/usr/local/etc/php/conf.d
    env_file:
      - .env
    ports:
      - "${PHP_PORT_EXTERNAL}:80"
    entrypoint: "php -S 0.0.0.0:80 -t /var/www"